CATEGORY_MAPPING = {
    "Headphones": "Headsets",
    "Headwear": "Helmets",
    "Map": "Barter Items",
    "Face Cover": "Helmets",
    "Vis. observ. device": "Face Cover",
    "Armor": "Armors",
    "Armored equipment": "Armors",
    "Armor Plate": "Armors",
    "Chest rig": "Rigs",
    "Backpack": "Backpacks",
    "Assault rifle": "Guns",
    "Handgun": "Guns",
    "Shotgun": "Guns",
    "Sniper rifle": "Guns",
    "Magazine": "Mods",
    "SMG": "Guns",
    "Assault carbine": "Guns",
    "Marksman rifle": "Guns",
    "Machinegun": "Guns",
    "Revolver": "Guns",
    "Grenade launcher": "Guns",
    "Flashhider": "Mods",
    "Assault scope": "Mods",
    "Reflex sight": "Mods",
    "Foregrip": "Mods",
    "Receiver": "Mods",
    "Charging handle": "Mods",
    "Handguard": "Mods",
    "Mount": "Mods",
    "Stock": "Mods",
    "Ironsight": "Mods",
    "Auxiliary Mod": "Mods",
    "Scope": "Mods",
    "Bipod": "Mods",
    "Gas block": "Mods",
    "Night Vision": "Mods",
    "Compact reflex sight": "Mods",
    "Special scope": "Mods",
    "Thermal Vision": "Mods",
    "UBGL": "Mods",
    "Comb. muzzle device": "Mods",
    "Comb. tact. device": "Mods",
    "Knife": "Guns",
    "Barrel": "Mods",
    "Pistol grip": "Mods",
    "Silencer": "Suppressors",
    "Throwable weapon": "Grenades",
    "Ammo container": "Ammo",
    "Port. container": "Containers",
    "Locking container": "Containers",
    "Common container": "Containers",
    "Random Loot Container": "Containers",
    "Money": "Barter Items",
    "Battery": "Barter Items",
    "Electronics": "Barter Items",
    "Lubricant": "Barter Items",
    "Jewelry": "Barter Items",
    "Other": "Barter Items",
    "Building material": "Barter Items",
    "Stimulant": "Medical",
    "Tool": "Barter Items",
    "Fuel": "Barter Items",
    "Flashlight": "Mods",
    "Household goods": "Barter Items",
    "Flyer": "Barter Items",
    "Multitools": "Barter Items",
    "Compass": "Barter Items",
    "Info": "Barter Items",
    "Repair Kits": "Barter Items",
    "Special item": "Barter Items",
    "Arm Band": "Barter Items",
    "Spring Driven Cylinder": "Mods",
    "Cylinder Magazine": "Mods",
    "Portable Range Finder": "Barter Items",
    "Radio Transmitter": "Barter Items",
    "Cultist Amulet": "Barter Items",
    "Mark of the Unheard": "Barter Items",
    "Planting Kits": "Barter Items",
    "Mechanical Key": "Keys",
    "Keycard": "Keys",
    "Drink": "Provisions",
    "Food": "Provisions",
    "Medical item": "Medical",
    "Drug": "Medical",
    "Medikit": "Medical",
    "Medical supplies": "Medical",
    "Ammo": "Ammo",
    "Ammo packs": "Ammo"
}