CATEGORY_MAPPING = {
    "Headphones": "Headsets",
    "Headwear": "Helmets",
    "Map": "Barter Items",
    "Face Cover": "Helmets",
    "Vis. observ. device": "Face Cover",
    "Armor": "Armors",
    "Armored equipment": "Armors",
    "Armor Plate": "Armors",
    "Chest rig": "Rigs",
    "Backpack": "Backpacks",
    "Assault rifle": "Guns",
    "Handgun": "Guns",
    "Shotgun": "Guns",
    "Sniper rifle": "Guns",
    "Magazine": "Mods",
    "SMG": "Guns",
    "Assault carbine": "Guns",
    "Marksman rifle": "Guns",
    "Machinegun": "Guns",
    "Revolver": "Guns",
    "Grenade launcher": "Guns",
    "Flashhider": "Mods",
    "Assault scope": "Mods",
    "Reflex sight": "Mods",
    "Foregrip": "Mods",
    "Receiver": "Mods",
    "Charging handle": "Mods",
    "Handguard": "Mods",
    "Mount": "Mods",
    "Stock": "Mods",
    "Ironsight": "Mods",
    "Auxiliary Mod": "Mods",
    "Scope": "Mods",
    "Bipod": "Mods",
    "Gas block": "Mods",
    "Night Vision": "Mods",
    "Compact reflex sight": "Mods",
    "Special scope": "Mods",
    "Thermal Vision": "Mods",
    "UBGL": "Mods",
    "Comb. muzzle device": "Mods",
    "Comb. tact. device": "Mods",
    "Knife": "Guns",
    "Barrel": "Mods",
    "Pistol grip": "Mods",
    "Silencer": "Suppressors",
    "Throwable weapon": "Grenades",
    "Ammo container": "Ammo",
    "Port. container": "Containers",
    "Locking container": "Containers",
    "Common container": "Containers",
    "Random Loot Container": "Containers",
    "Money": "Barter Items",
    "Battery": "Barter Items",
    "Electronics": "Barter Items",
    "Lubricant": "Barter Items",
    "Jewelry": "Barter Items",
    "Other": "Barter Items",
    "Building material": "Barter Items",
    "Stimulant": "Medical",
    "Tool": "Barter Items",
    "Fuel": "Barter Items",
    "Flashlight": "Mods",
    "Household goods": "Barter Items",
    "Flyer": "Barter Items",
    "Multitools": "Barter Items",
    "Compass": "Barter Items",
    "Info": "Barter Items",
    "Repair Kits": "Barter Items",
    "Special item": "Barter Items",
    "Arm Band": "Barter Items",
    "Spring Driven Cylinder": "Mods",
    "Cylinder Magazine": "Mods",
    "Portable Range Finder": "Barter Items",
    "Radio Transmitter": "Barter Items",
    "Cultist Amulet": "Barter Items",
    "Mark of the Unheard": "Barter Items",
    "Planting Kits": "Barter Items",
    "Mechanical Key": "Keys",
    "Keycard": "Keys",
    "Drink": "Provisions",
    "Food": "Provisions",
    "Medical item": "Medical",
    "Drug": "Medical",
    "Medikit": "Medical",
    "Medical supplies": "Medical",
    "Ammo": "Ammo",
    "Ammo packs": "Ammo",
}

SCAV_CASE_TYPES = ["₽2500", "₽15000", "₽95000", "Moonshine", "Intelligence"]

DEFAULT_TRACKED_ITEMS = [
    "Pack of sugar",
    "Bottle of Fierce Hatchling moonshine",
    "Intelligence folder",
]

# Error message will read 404 - Not Found, then on new line, one of:
MESSAGES_404 = [
    "Just like that last GPU you searched for.",
    "Page not found, but don’t worry, it’ll extract before you do.",
    "You didn’t bring enough rubles for this route, comrade.",
    "This page is camped by Killa. Good luck.",
    "Wrong keycard. Try again, rat.",
    "This page was found in a dead SCAV’s backpack, but now it’s gone.",
    "Page not found. Maybe it desynced?",
    "You loaded into the wrong raid. Try again.",
]

MESSAGES_403 = [
    "Nice try, but you don’t have the key for this door.",
    "Access denied. Maybe Fence doesn’t trust you enough?",
    "You need to be Level 15 to access this trader… oh wait, wrong game.",
    "Prapor says no. Try again later.",
    "This area is locked. Find a Labs keycard, then we’ll talk.",
    "Your access has been revoked… probably because you scav killed.",
    "You don’t have enough reputation to enter. Go grind some more quests.",
    "You need higher loyalty with Therapist to access this page.",
]

MESSAGES_500 = [
    "Looks like Tarkov servers are down… again.",
    "The game crashed, and now so did this page.",
    "An unexpected error occurred. Just like when your game freezes mid-raid.",
    "This page took too much damage and blacked out.",
    "Something went wrong, kind of like your last raid.",
    "Your request got head-eyes’d by a TTV chad.",
    "Our backend desynced. Please wait for a reconnect...",
    "This page hit an invisible Sturman guard. Try again.",
]
