"""add force_password_change to user

Revision ID: 11057ef75be9
Revises: ccaaa0a5c616
Create Date: 2026-02-25 16:53:34.155035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11057ef75be9'
down_revision = 'ccaaa0a5c616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('force_password_change', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('force_password_change')

    # ### end Alembic commands ###
