"""add indexes and constraints

Revision ID: 15c4ad24b6eb
Revises: c1bcf30cb7ca
Create Date: 2026-02-17 20:03:26.867189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c4ad24b6eb'
down_revision = 'c1bcf30cb7ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scav_case', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scav_case_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('scav_case_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scav_case_item_scav_case_id'), ['scav_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scav_case_item_tarkov_id'), ['tarkov_id'], unique=False)

    with op.batch_alter_table('tarkov_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tarkov_item_tarkov_id'), ['tarkov_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarkov_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tarkov_item_tarkov_id'))

    with op.batch_alter_table('scav_case_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scav_case_item_tarkov_id'))
        batch_op.drop_index(batch_op.f('ix_scav_case_item_scav_case_id'))

    with op.batch_alter_table('scav_case', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scav_case_user_id'))

    # ### end Alembic commands ###
