"""fix FK naming issue

Revision ID: a4c9403a490c
Revises:
Create Date: 2025-02-11 16:00:30.675911

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a4c9403a490c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scav_case_item", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column(
            "tarkov_id",
            existing_type=sa.TEXT(),
            type_=sa.String(length=50),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "name",
            existing_type=sa.TEXT(),
            type_=sa.String(length=100),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "price", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=False
        )
        batch_op.create_foreign_key(
            "fk_scav_case_item_scavcase", "scav_case", ["scav_case_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_scav_case_item_tarkov", "tarkov_item", ["tarkov_id"], ["tarkov_id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scav_case_item", schema=None) as batch_op:
        batch_op.drop_constraint("fk_scav_case_item_tarkov", type_="foreignkey")
        batch_op.drop_constraint("fk_scav_case_item_scavcase", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "scav_case", ["scav_case_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.alter_column(
            "price", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=False
        )
        batch_op.alter_column(
            "name",
            existing_type=sa.String(length=100),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "tarkov_id",
            existing_type=sa.String(length=50),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    # ### end Alembic commands ###
