"""Rename Entry to ScavCase and ScavCaseItem to ScavCaseItem

Revision ID: b2e8b04aa791
Revises: 3d903b6462fa
Create Date: 2025-02-08 11:56:18.281152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e8b04aa791'
down_revision = '3d903b6462fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scav_case_item")
    op.drop_table("scav_case")
    op.rename_table('entry_item', "scav_case_item")
    op.rename_table('entry', "scav_case")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('cost', sa.FLOAT(), nullable=False),
    sa.Column('_return', sa.FLOAT(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('number_of_items', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entry_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tarkov_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('entry_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], ),
    sa.ForeignKeyConstraint(['tarkov_id'], ['tarkov_item.tarkov_id'], name='fk_ScavCaseItem_tarkovitem'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
