"""add discord_id and discord_username to user

Revision ID: b4c2dc0b5357
Revises: 11057ef75be9
Create Date: 2026-02-25 18:43:34.792465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4c2dc0b5357'
down_revision = '11057ef75be9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('discord_username', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint('uq_user_discord_id', ['discord_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_discord_id', type_='unique')
        batch_op.drop_column('discord_username')
        batch_op.drop_column('discord_id')

    # ### end Alembic commands ###
