"""add scav_case_global_dashboard_layout to user

Revision ID: c1bcf30cb7ca
Revises: a4c9403a490c
Create Date: 2026-02-17 08:44:21.538649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1bcf30cb7ca'
down_revision = 'a4c9403a490c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scav_case_global_dashboard_layout', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('scav_case_global_dashboard_layout')

    # ### end Alembic commands ###
