"""add via_discord to scav_case

Revision ID: f32c40eab45c
Revises: b4c2dc0b5357
Create Date: 2026-02-25 19:18:34.732224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f32c40eab45c'
down_revision = 'b4c2dc0b5357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scav_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('via_discord', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scav_case', schema=None) as batch_op:
        batch_op.drop_column('via_discord')

    # ### end Alembic commands ###
